# Generated by Django 2.2.5 on 2020-01-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('az', 'Azeri (Latin)'), ('be', 'Belarusian'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dv', 'Divehi'), ('el', 'Greek'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Farsi'), ('fi', 'Finnish'), ('fo', 'Faroese'), ('fr', 'French'), ('gl', 'Galician'), ('gu', 'Gujarati'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('id', 'Indonesian'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mi', 'Maori'), ('mk', 'FYRO Macedonian'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('nb', 'Norwegian'), ('nl', 'Dutch'), ('ns', 'Northern Sotho'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('ps', 'Pashto'), ('pt', 'Portuguese'), ('qu', 'Quechua'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sa', 'Sanskrit'), ('se', 'Sami (Northern)'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tl', 'Tagalog'), ('tn', 'Tswana'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('ts', 'Tsonga'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek (Latin)'), ('vi', 'Vietnamese'), ('xh', 'Xhosa'), ('zh', 'Chinese'), ('zu', 'Zulu')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
