# Generated by Django 2.2.5 on 2020-01-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='value',
            field=models.TextField(default='1'),
        ),
    ]
