# Generated by Django 2.2.5 on 2020-01-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Price'),
        ),
    ]
